### ISSUE TITLE
Integration of Fanuc CNC Controllers 

### ISSUE THREAD

**Issue by sagardubal** [plcpeople/honcho#3]
Hello! 

We have been using the S7 library that you have made. I would like to know if you could develop something similar for for Fanuc CNC Controllers in node.js . It will be a great project to work on.

**Comment by plcpeople** [comment]
I think this would be difficult for us as we don't have access to a Fanuc CNC controller, and there doesn't seem to be a lot of documentation on the communication protocols used.

**Comment by plcpeople** [comment]
I am closing this issue as there are no plans to add support for Fanuc CNC Controllers right now.  If ever we did, it would be added in a new project that would be referenced from Honcho, rather than added to Honcho itself.
